### ISSUE TITLE
Bug QCM, certains valeurs des choix sont incorrect

### ISSUE THREAD

**Issue by ThorsThunder04** [The-Weather-TEAM/Life-SCORE#100]
C'est un anomalie que j'ai rencontré. Je crois pas que c'est un erreure causé par mon changement au des choix de csv en dico. ça pourait etre a cause d'un bug quand on relance pour aller au prochain question du QCM. Mais encore, je suis pas du tout sur. Je ne vois pas d'ou ça vien.

(quand je dit identique je veut dire du meme valeur 0 ou 1 et puis les autres sont identique, mais de l'autre valeur 0 ou 1)
Exemples:
- tout les choix identiques sauf le dernier => le dernier valeur prend la valeur de l'avant dernier valeur
- tout les choix identiques sauf les deux derniers => L'avant dernier prend la valeur de celui avant lui, et le dernier prend la bonne valeur.

Ainsi de suite si on prend les 3 dernier identiques. Mais ça n'arrive pas si on prend par example que les deux premier identiques.

**Comment by Farenc21** [comment]
résolu dans le commit [3afe2ae](https://github.com/The-Weather-TEAM/Life-SCORE/commit/3afe2ae23282cbb9260878092521ffaa2b690af9) :)
