### ISSUE TITLE
Notes qui sont maintenant de 0 ????

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#103]
![image](https://user-images.githubusercontent.com/104134380/229204478-95d1b2b1-f011-4747-90d0-a0b0361f92da.png)
@Farenc21 jsp si t'as modifié quelque chose mdrrr, j'ai marqué ça en testant si insee != 0 mais quoi qu'il arrive on a 0, j'ai créé une nouvelle braznche dcp pour avancer de mon côté

**Comment by bosy0** [comment]
![image](https://user-images.githubusercontent.com/104134380/229205189-d3e7f9e4-db82-408d-983d-26f319b746ce.png)

c'est l'erreur si on enlève le try exept

**Comment by Farenc21** [comment]
545888f29df24a9e569e46ded4de09d1b1befeca
ça devrait être bon
