### ISSUE TITLE
Problème arrondissement / géoloc

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#105]
Je peux essayer de le résoudre stv thor

![image](https://user-images.githubusercontent.com/104134380/229278636-0a6a43ad-5a7b-4b90-93dd-4f91468c7d12.png)

**Comment by ThorsThunder04** [comment]
Je crois que je l'ai resolute, mais en meme temps j'ai aucune idee quoi comme ville tu a mis. Tu a mis quoi comme ville?

**Comment by bosy0** [comment]
j'ai testé en mettant "Marseille 2e arrondissement" je crois

**Comment by ThorsThunder04** [comment]
mais pour les arrondissment il faut mettre dans ce cas "Marseille_2" non?

**Comment by bosy0** [comment]
Aaaah non plus maintenant, j'utilise plus le csv modifié qu'on utilisait

**Comment by bosy0** [comment]
Si tu veux je te modifie le code pour t'envoyer "Marseille_2"

**Comment by ThorsThunder04** [comment]
hh non just, il faut dire ces choses. Sa a aussi cassé un autre truque je crois au fonction `recup_donnees_simple_affine()` dans classe. Car quand je fait un ville avec un arrondissmenet il me ressort cette erreur:
![image](https://user-images.githubusercontent.com/87436831/229279852-af88562e-ffd2-424c-9011-1e04bad96c0a.png)

**Comment by ThorsThunder04** [comment]
Le problem devrais etre resolue maintenant

**Comment by bosy0** [comment]
Désolé thor, mais ça marche toujours pas :(
J'ai testé avec Marseille 2 earrondissement mais ça plante

![image](https://user-images.githubusercontent.com/104134380/229285708-b4037c99-80a7-4c27-a9e1-276180ab3fdc.png)


j'ai enlevé l'arrondissement temporairement ducoup
