### ISSUE TITLE
Page paramètre bloque le programme

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#106]
Je vous explique :

- On cherche une ville
- La nouvelle page se lance et l'animation de la note se lance
- Si on clique sur la page paramètres, ça bloque l'animation et le bouton 'chercher une nouvelle ville' ne peut pas apparaître 

Il faudrait désactiver le bouton le temps de l'animation, qu'en pensez-vous ?

**Comment by Farenc21** [comment]
J'ai bloqué les boutons le temps de l'animation et l'ai réactivé une fois celle-ci terminée
