### ISSUE TITLE
Page blanche sur linux entre la recherche de la ville et la page de notation

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#108]
JSP pourquoi, ça n'affiche pas le 'veuillez patienter' et ça passe direct à la prochaine page sauf que c'est blanc pendant 3 ou 4 secondes

**Comment by Farenc21** [comment]
Reteste je pense qu'en modifiant certains appel ça devrait marcher maintenant

**Comment by bosy0** [comment]
T'es trop fort ça marche
