### ISSUE TITLE
Désactiver le redimensionnement de la fenêtre une fois qu'on affiche la dernière page

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#116]
mais dans les autres fenêtres on peut

ça créer un gros pâté

**Comment by Farenc21** [comment]
je m'en charge il faut mettre fenetre.resizable(False,False) je crois

**Comment by Farenc21** [comment]
mettre le resizable en False gache l'animation  (ya un gros chargement tt en blanc). Les tailles minimales autorisées sont censées maintenir cet ordre dans les widgets du moins sur mon pc il n'y a aucun problème

**Comment by Farenc21** [comment]
C'est risqué ducoup pcq si on avait une taille petite on pourra plus la modifier, je propose de forcer le plein écran

**Comment by bosy0** [comment]
go
