### ISSUE TITLE
Revoir fonctions pour noter pour créer plus de contrastes avec les données

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#118]

**Comment by Farenc21** [comment]
je sais pas si on a travaillé une fonction pareille mais faudrait avoir ce genre de valeurs peut être :
25 -> 10
50 -> 50
75 -> 100 
plus  ou moins 

ou alors : 
on fait juste +20 mais bon c'est nul comme résolution

**Comment by Farenc21** [comment]
on peut calculer l'écart à 50 et lui appliquer un coefficient en fonction
je m'explique : 
Un truc du style
```ecart = note - 50 (entre 0 et 50)
if ecart < 0 :
     note_finale = note * ecart/50 (pour avoir une proportion)
else:
     note_finale = note * ((ecart/50) + 1)

**Comment by bosy0** [comment]
ouais je pense qu'on va partir là-dessus, provisoirement j'ai juste augmenté le coef directeur en calculant les notes

**Comment by bosy0** [comment]
Mais oui au pire on fait passer la note premièrement dans la fonction affine puis après dans une fonction du style

**Comment by bosy0** [comment]
J'ai utilisé lers fonction sigmonides
