### ISSUE TITLE
Deux trois trucs

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#121]
- Les notes sont toujours supérieures quand on recherche une ville quand ce qu'il y a marqué dans les villes voisines

**Comment by bosy0** [comment]
- mettre un texte pour prévenir qu'il n'y a pas internet peut être

**Comment by Farenc21** [comment]
1) fenêtre.resizable(False,False)
2) il faut trouver un autre texte explicatif tu as raison
3) normalement il faut mettre Paris 2e arrondissement tu peux préciser ce qu'il se passe ?
4) on s'en occupe rapidement
5) je pense pas pcq on a plus beaucoup de places
6) oui on peut le mettre directement dans la textbox pour faciliter
7) t'as testé deux villes voisines pour comparer ? Le problème vient peut être des notes de météo mal gérées
8) non c'est bon ça arrive pas si fréquemment que ça de pas avoir internet

**Comment by bosy0** [comment]
Ouais regarde pour le7ème
![image](https://user-images.githubusercontent.com/104134380/230787726-c6d6b9fd-bed6-41f2-98f6-600d02f4dbcf.png)
![image](https://user-images.githubusercontent.com/104134380/230787743-88e3ea97-a373-40c1-bb0d-f01acddfa99a.png)

**Comment by Farenc21** [comment]
D'accord compris le problème vient de 3 choses possibles :
- Tous les csv ne sont pas pris en compte jsp pourquoi
- Les coefficients ne sont peut etre pas pris en compte pour les autres villes
- Les notes n'entrent pas en jeu 

perso je miserai sur les coefficients

**Comment by bosy0** [comment]
ah yes faudrait voir, @ThorsThunder04 tu penses que c'est les coefs ?

**Comment by ThorsThunder04** [comment]
Il y a aussi l'effet inversé avec des villes où c'est supérieur quand c'est le bille qu'on recherche. Je mon théorie était que c'est parce que on ne prend pas en compte le météo dans les villes voisins.

**Comment by ThorsThunder04** [comment]
J'ai testé avec les coefs en mettant les deux a 1. Et il y a encore les mems valeurs dans les villes voisins, mais just des notes plus haut pour le ville lui meme (vue qu'il y a pas de coef 0.5). 
Donc je crois pas que c'est le coef qui fait cette bug.

**Comment by Farenc21** [comment]
Si changer les coefficients n'affecte pas la note des autres villes il me semble que c'est pour ça qu'on a pas les bons résultats justement
