### ISSUE TITLE
Bloquer les boutons quand la page téléchargement est lancé

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#122]
ligne 206 j'ai rajouté pour bloquer mais je sais pas où débloquer les boutons.

Si on le fait pas et qu'on clique sur un bouton alors qu'on télécharge ça bloque tout

**Comment by Farenc21** [comment]
Je fais des test j'essaie de trouver le moment exact où le téléchargement se termine

**Comment by Farenc21** [comment]
C'est bon ligne 234 juste après erreur_maj = update.executer(...)
