### ISSUE TITLE
Bug au niveau de coefs si la note est 'None'

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#125]
Je te donne l'issue Thor parce que c'est ta partie, j'ai peur de tout casser hahaha
![image](https://user-images.githubusercontent.com/104134380/230970429-a38fbc2d-88c7-400e-ab60-e3988a64ffbd.png)

En gros j'ai ça (ça arrive quand on cherche Salies ou Paris)
Je pense que ça vient de fait que la note de m2_maisons c'est 'None' vu qu'on a pas la donnée dans le csv en question, et c'est la même pour plusieurs autres csv.

**Comment by ThorsThunder04** [comment]
Fix avec un "if" qui verifie si le critere est bien dans la liste de notes.
Ne ne sais pas pourquoi cela arrive tout d'un coup, car il marchais avec Paris avant. Mais en tout cas le fix marche.

![image](https://user-images.githubusercontent.com/87436831/230982169-3de8acd6-dc07-4a10-8999-20db739f52ef.png)
