### ISSUE TITLE
comtper_par_population marche seulement quand la colonne des données est plus grande que celle du code insee

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#126]

**Comment by Farenc21** [comment]
Je pense l'avoir résolu dans ma dernière issue

**Comment by bosy0** [comment]
je push l'ancienne version qui marche :/

**Comment by Farenc21** [comment]
Le fameux on met la poussière sous le tapis

**Comment by bosy0** [comment]
bhahahahaha, non mais  après ça marche..

**Comment by bosy0** [comment]
j'arrive pas à trouver je vais péter un cable là avec tous ces csv

**Comment by Farenc21** [comment]
Je l'ai expliqué le problème juste en essayant de le résoudre j'ai aggravé les choses mais je pense qu'on peut garder sur cette idée de renommer les choses
