### ISSUE TITLE
Villes homonymes (Verdun)

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#127]
![image](https://user-images.githubusercontent.com/104134380/231569128-c589a02a-0b61-4b7a-af58-91190bba5977.png)

Soit un agrandit la zone de recherche ??
Ou alors on marque juste "Pas de ville dans les alentours" ?

Qu'en pensez-vous ?

**Comment by Farenc21** [comment]
MDRRR c(est pas normal ça il est censé récupérer les 10 plus proches dans le département et je doute que Verdun soie la seule ville de son département

**Comment by Farenc21** [comment]
Ya du avoir une erreur dans les calculs ce qui a empéché d'afficher correctement le kppv sûrement le fait de push l'ancienne version (quand je te disais de remettre une version qui marche je parlais pas de tout le programme faut pas faire une retour en arrière complet juste ce qui nous intéresse)

**Comment by bosy0** [comment]
aaah ouais ok, après verdun ça le fait depuis longtemps, y'a aussi un truc genre viols-le-fort ou un nom comme ça où y'a aucune ville autour

**Comment by Farenc21** [comment]
Il doit donc y avoir plusieurs viols-le-fort je pense

**Comment by Farenc21** [comment]
Précision pour ceux qui sont extérieurs au code : les villes homonymes (plusieurs villes ont rigoureusement le même nom) ne permettent pas d'activer les kppv a cause de problèmes de comparaisons avec les codes

**Comment by bosy0** [comment]
perfect
