### ISSUE TITLE
Idée de malade mais faut le voir qu'à la fin

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#17]
Genre quand on recherche ça nous liste toutes les villes / villages disponibles vu qu'on a un csv avec tout ça
Je sais pas si c'est possible mais ça peut prouver nos compétences de giga chad

**Comment by Spaghet34** [comment]
je suis pas sur d'avoir compris le truc genre une recherche intelligente ?
Si c'est ça faudrait une liste ou un string avec toutes les 30000communes mais jsp si tkinter l'autorise

**Comment by bosy0** [comment]
ah ouais c'est pas ouf, mais genre au bout de genre 5 caractères ça fait la recherche et ça nous donne un truc comme dans google quoi
![image](https://user-images.githubusercontent.com/104134380/211083169-33d805b6-3ec4-4029-ad0c-84a3a4e3d0c9.png)
Genre ça

**Comment by Spaghet34** [comment]
https://youtu.be/0CXQ3bbBLVk?t=799
Ya un timecode pour voir a quoi ressemblerait le programme mais je pense que ce sera pas possible avec 30 000 lignes

**Comment by bosy0** [comment]
ouais faut voir à la fin stv je m'en occupe mais on regarde une fois que le code est bien avancé

**Comment by bosy0** [comment]
Je me suis renseigné et c'est vraiment une galère ouais mdr
