### ISSUE TITLE
Autre version pour le qcm

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#19]
J'ai trouvé une vidéo il faut que je vous l'envoie mais en gros au lieu de faire 2 choix possible on fait une barre à remplir de 0 à 100 comme ça c'est pas binaire et la personnalisation sera plus juste mais c'est pour plus tard si on a le temps ça

**Comment by bosy0** [comment]
On peut l'utiliser directement avec customtkinter c'est trop cool

**Comment by Farenc21** [comment]
Non c'est bon finalement notre QCM suffit faut juste qu'on puisse récupérer les valeurs et bien les implémenter dans le calcul de la note
