### ISSUE TITLE
Nouveau logo 

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#21]
à voir une fois le code terminé :
un nom sympa parce que life score c'est bidon
et un vrai logo qui suit notre charte graphique

**Comment by bosy0** [comment]
Avec un logo peut être animé mais faut voir si on peut afficher ça avec tkinter peut être des gifs

**Comment by bosy0** [comment]
life score enfait c'est bien mdr

**Comment by Spaghet34** [comment]
J'ai sous 4 versions différentes un truc fais en 30 secondes mdrrr

![LifeScore](https://user-images.githubusercontent.com/101197359/212490137-a847cb85-41c4-4496-87a7-4799d713a2fc.jpg)

https://user-images.githubusercontent.com/101197359/212490139-c5d376df-fb79-4343-a642-fa14eb1dbb7d.mp4

![LifeScore](https://user-images.githubusercontent.com/101197359/212490142-1d713c1e-0593-4fdc-b892-4ff940e29d28.png)

[LifeScore.pdf](https://github.com/The-Weather-TEAM/Life-SCORE/files/10418553/LifeScore.pdf)

**Comment by Spaghet34** [comment]
Et je peux faire le même sans "note de ville" pour le mettre sur le tkinter

**Comment by bosy0** [comment]
C'est bon ducoup ?
