### ISSUE TITLE
programme pour installer toutes les biliothèques

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#23]
Merci Thor ahaha
mais en gros si les gens n'ont pas tkinter faut bien qu'il le télécharge.
On va faire un fichier .exe mais il faut toujours mettre le python pour qu'ils aient accès au code

**Comment by sanzelda** [comment]
Je ne comprend pas ce que tu demande.

**Comment by bosy0** [comment]
Tu l'a déjà fait c'était le fichier [requirements.txt](https://github.com/The-Weather-TEAM/Life-SCORE/blob/main/requirements.txt) !
