### ISSUE TITLE
Autre calcul du pourcentage

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#24]
Voir si les métadonnées nous donnent pas la taille du fichier pour pourvoir le diviser et avec la taille totale des fichiers pour avoir un pourcentage plus homogène

**Comment by Spaghet34** [comment]
je suis pas sur de suivre tu peux me l'expliquer stp ? @bosy0

**Comment by bosy0** [comment]
En gros je calcule le pourcentage pour les majs en fonction des csv qui restent à traiter

Mais y'en a ils font genre 1mo et d'autres 45mo ducoup je voudrais voir dans mon code si c'est possible de récupérer la taille des csv pour avoir un calcul du pourcentage plus précis.

Après c'est un détail mdr

**Comment by bosy0** [comment]
On a rien qui nous donne la taille du fichier à télécharger=, ducoup ça tombe à l'eau hahaha
mais pas grave c'est juste un détail

**Comment by Spaghet34** [comment]
Et os.stat() ? Ou stats() jsp ça te donne la taille en Bytes donc octet je crois et on peut réfléchir à une fonction simple qui fait sur 100

**Comment by bosy0** [comment]
ouais mais c'est une fois qu'on l'a de stocké sur notre pc, moi je voudrais récupérer les infos d'un fichier non téléchargé et data.gouv.fr ils nous donnent pas ça :/
