### ISSUE TITLE
Les accents ne marchent pas

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#27]
pour rechercher / afficher une commune

**Comment by bosy0** [comment]
@Spaghet34 en gros j'ai testé avec Béziers et ça marchait pas mdrr, mais c'est surtout quand on affiche la ville après c'est des détails quoi

**Comment by bosy0** [comment]
@Spaghet34 j'ai bien testé ça marche pas quand on rentre une ville avec des accents :/

**Comment by Spaghet34** [comment]
J'ai réglé le soucis @bosy0 En remplaçant les accents par leurs équivalents non accentué

**Comment by bosy0** [comment]
trop biennnnnnnnnnnnn
