### ISSUE TITLE
Lancer le code ssi on est sur windows et si la version de python est la dernière (ou presque)

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#31]

**Comment by Spaghet34** [comment]
Tant qu'on a python, on pourrait pas le lancer sur Mac/linux ?

**Comment by bosy0** [comment]
Sur linux ouais, mais mac je vais devoir modifier mon fichier update et les classes parce que la bibliothèque fonctionne pas pareil sur mac mdrr clc apple

**Comment by Spaghet34** [comment]
Finalement c'est que windows alors jpense on peut juste le mettre dans les prérequis genre : 
"windows 10 ou windows 11"

**Comment by bosy0** [comment]
yes c'est pour l'instant ce qu'on a
