### ISSUE TITLE
Si on donne une ville étrangère afficher un message d'erreur spécial 

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#34]

**Comment by Spaghet34** [comment]
trop problématique de différencier une ville étrangère d'une ville inexistante faudrait parcourir un csv avec genre 2 millions de ligne ça prendrait une minute

**Comment by bosy0** [comment]
@Spaghet34 on peut directement le faire si is_ville_france_v2 == false non ?

**Comment by Spaghet34** [comment]
@bosy0 là la ville n'est pas française mais j'ai rien qui me prouve qu'elle existe genre ya aucune différence entre "Washington DC" et"blablaville"

**Comment by bosy0** [comment]
Aaaah ouais j'avoue, à voir dcp avec une api genre le truc de météo mais seulement si on a internet
