### ISSUE TITLE
Test connection avec des msg box (fenêtres windows d'erreur)

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#35]

**Comment by bosy0** [comment]
Avec genre un bouton réessayer et un bouton annuler qui ferme le programme

**Comment by bosy0** [comment]
@Spaghet34 si tu peux m'expliquer un de ces quatre comment marche tkinter messagebox ça serait top comme ça je fait une interface si il y a un problème au niveau de la connexion

**Comment by Spaghet34** [comment]
j'ai expliqué la classe Message sur instagram mais jsp si c'est ca enfait ce que tu me demandais.
Sers toi de mon "msg_principal" pour voir comment je l'utilise tu vas voir c'est comme tout objet de tkinter c'est facile à prendre en main  une fois que t'as la syntaxe puis les attributs sont évidents aussi (font, width, text,...)

**Comment by Spaghet34** [comment]
Ok je viens de comprendre je connaissais pas mais t'as un truc regarde
#Warning (/!\)
tkinter.messagebox.showwarning(title='Attention - Problèmes de connexion', message='Attention ,blablablablabla', **options)
#Error (X)
tkinter.messagebox.showerror(title='Erreur - x', message='Vous n'avez ni accès à internet ni aux fichiers nécessaires', **options)

**Comment by bosy0** [comment]
parfait je regarde ça et je vas me renseigner pour faire quelque chose de quali merci

**Comment by Farenc21** [comment]
Il me semble que @bosy0 Remplace ça par des images, reouvre l'issue si tu veux garder les messagebox

**Comment by bosy0** [comment]
Yesss ça sera plus classe
