### ISSUE TITLE
Fonction qui ferme le programme

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#36]
Qu'on peut utiliser dans le test réseau ou s'il y a un bug / erreur ou juste pour quitter

**Comment by Spaghet34** [comment]
Si ya une erreur juste on ouvre la page d'erreur ça me semble suffisant q

**Comment by bosy0** [comment]
oui mdr c'est mieux

**Comment by Farenc21** [comment]
`sys.exit()`
Mets le où tu veux, je vais créer le boutton quitter
