### ISSUE TITLE
Si il n'y a pas de données de la commune sur un csv, passer la notation

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#42]
Et plus tard dans le code on si on met un visu pour chaque données on pourra spécifier que la donnée est inconnue

**Comment by bosy0** [comment]
Et si il y a aucune données bein on dit que la commune n'est pas notable

**Comment by bosy0** [comment]
> Et si il y a aucune données bein on dit que la commune n'est pas notable

On s'en occupe dans une autre issue

**Comment by Spaghet34** [comment]
ce que je fais c'est de try toute la fonction sauf le return et puis je mets ca derrière :
`except IndexError : #SI pas de données
            return None`
Mais c'est pas automatique alors je ferme l'issue mais si tu préfère qu'on code un truc automatique pour toutes les notes de la vills reouvre l'issue

**Comment by bosy0** [comment]
trop fort
