### ISSUE TITLE
Problème (?) de sécurité pour requirements.txt

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#46]
https://github.com/The-Weather-TEAM/Life-SCORE/security/dependabot

@sanzelda C'est normal ? ahahah

**Comment by sanzelda** [comment]
Oui c'est normal. J'ai mis des versions fix aux modules car c'est la bonne pratique. Il y avais surement des bugs avec le version de pillow precedent, donc ça nous previent enfaite just de mettre le version a un version plus recent qui n'a pas ces bugs. 
En gros, the pillow sur mon PC n'est pas a jours XD

**Comment by bosy0** [comment]
Aaaah ok aucun souci alors ! Top
