### ISSUE TITLE
Bouton "rechercher une nouvelle ville" ne marche pas

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#48]
c:\Users\natha\Documents\GitHub\Weather-NSI\code\classes.py:232: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  cr = p.read_csv(fichier,delimiter=",",usecols=['Nom1','Nom2','Nom3','Code_INSEE']) #encoding pour pouvoir avoir les accents (ne marche pas)
c:\Users\natha\Documents\GitHub\Weather-NSI\code\classes.py:284: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data_sport = p.read_csv(self.repertoire + '/CSV/2020_Communes_TypEq.csv',delimiter=",",usecols=['ComInsee','Nombre_equipements'])
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\natha\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\natha\Documents\GitHub\Weather-NSI\code\LifeSCORE.py", line 363, in <lambda>
    btn_Retour = Button(windowScore, width=20, height=3, command=lambda:retour_pages(windowScore,"page2"), bg='#B9F7D0', text= "Noter une autre ville", font=('Bold',20))
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\natha\Documents\GitHub\Weather-NSI\code\LifeSCORE.py", line 215, in retour_pages
    change_etat_btn(btn)
  File "c:\Users\natha\Documents\GitHub\Weather-NSI\code\LifeSCORE.py", line 223, in change_etat_btn
    if bouton['state'] == NORMAL:
       ~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by bosy0** [comment]
@Spaghet34 c'est à propos des états des boutons mdrr j'ai essayé de voir mais c'est trop chiant personne n'a cette erreur

**Comment by Spaghet34** [comment]
Corrigé ducoup c'était juste le second attribut qui devait être un bouton alors que j'y rentrais le string "Page 2" petite erreur d'inattention
