### ISSUE TITLE
Fenêtre paramètres dans le menu principal 

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#49]
Genre une fenêtre avec les crédits bien sûr,
Mais surtout on peut choisir d'effacer les donnés utilisateur (si on vient à les stocker)
Et on peut choisir la fréquence de recherche de mise à jour / faire une mise à jour maintenant

**Comment by Spaghet34** [comment]
Jt'ouvre le bouton et la page qui va avec mais à voir ouais

**Comment by bosy0** [comment]
parfait thanks

**Comment by Spaghet34** [comment]
Je préfère la réouvrir l'issue le temps qu'on ai vraiment rajouté ce qui nous interessr :
> Changer la fréquence de maj
> Update le fond

**Comment by bosy0** [comment]
Ok, on bosse ça avec @sanzelda, pour l'instant on veut :
- Supprimer les données utilisateur (pour refaire le QCM)
- Modifier le thème (avec fenêtre pour redémarrer le programme)
- Modifier la fréquence de mise à jour (valeur dans update qu'on peut changer d'endroit)

**Comment by bosy0** [comment]
fréquence de maj sauvegardée sur options.csv

**Comment by Farenc21** [comment]
est-ce que ya une fonction python ou os pour fermer et relancer le programme ? Si oui il faut l'associer au bouton (appliquer les changements)

**Comment by bosy0** [comment]
Jme renseigne

**Comment by bosy0** [comment]
Ça peut marcher avec os.execl

**Comment by bosy0** [comment]
Je commence à m'en occuper, faudrait qu'il y ait ;
- Paramètres de fréquence de màj et vérification à l'instant T de mises à jour
- Apparence de l'appli (thème sombre/clair/système) + couleur ??
- Données utilisateur : supprimer les données et voir les conditions (pour bien spécifier qu'on utilise que ça pour le logiciel)
- Crédits et rapport de bugs (qui redirige soit vers un truc google forms soit ici)

**Comment by Farenc21** [comment]
La couleur c'est fait faut juste bien les placer (peut etre agrandir la taille minimale de la fenetre)
