### ISSUE TITLE
Boutons Oui et Non petite erreur

### ISSUE THREAD

**Issue by Spaghet34** [The-Weather-TEAM/Life-SCORE#52]
Il y a une erreur sur les animations qui se lance quand on passe d'une page à l'autre

**Comment by Spaghet34** [comment]
Ces boutons ne posent plus d'erreur (je faisais .destroy( ) à deux reprises mdrr jsuis bête) mais ya encore une erreur similaire (soyez à l'affut si vous voyez une suppression répétée

**Comment by Spaghet34** [comment]
J'ai mal pris en compte l'issue 50 qui n'a enfait rien à voir donc je reouvre celle là

**Comment by bosy0** [comment]
ça marche sur spyder sur l'ordi du lycée mdrrr mais pas sur vscode, faut voir peut être une incompatibilité entre vscode et customtk

**Comment by Spaghet34** [comment]
C'est bon l'erreur venait du fait que l'on avait plusieurs "Main" fenêtres donc j'ai mis toutes les main dans une seule
