### ISSUE TITLE
Rendre inaccessible la fenêtre principale tant que la secondaire est pas fermée

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#53]
Vous savez quand ça clignote pour nous dire qu'il faut fermer cette page pour pouvoir accéder à l'autre

**Comment by Spaghet34** [comment]
Je sais qu'on peut désactiver les boutons faut voir si on peut le faire avec une page (chercher tous les attributs d'une page customtkinter)

**Comment by Spaghet34** [comment]
Je ne penses pas que ce soit faisable ya des sites qui en parlent mais disent que c'est dangereux pcq tu peux aisément te softlock

**Comment by bosy0** [comment]
Aie ça marche alors on laisse tomber vaut mieux
