### ISSUE TITLE
Enlever les espaces quand on fait une recherche

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#54]
mais juste à la fin (genre on regarde le n ième caractère, et tant que c'est un espace on supprime)

genre 
beziers_ (_ = un espace) ne marche pas

**Comment by Spaghet34** [comment]
Problème réglé j'ai fait un str qui prend toutes les lettres minuscules, majuscules et les chiffres et j'ai juste mis
`while self.ville[-1] not in chaine_lettres : 
      self.ville[:-1] #Recupere tous les caractères sauf le dernier`

**Comment by Spaghet34** [comment]
Le strip() enlevé tt les espaces même au milieu donc on peut pas écrire "paris 1" a voir si une autre fonction existe

**Comment by bosy0** [comment]
à termes tu pense que ça serait cool d'avoir une sélection des arrondissement ?
Genre si c'est une ville qui a des arrondissement style Paris, bein une nouvelle fenêtre nous demande de choisir entre ses arrondissement
ça peut nous éviter d'essayer de résoudre le problème

**Comment by Spaghet34** [comment]
Je l'ai résolu enfait c'est moi qui lisait genre "Paris 7" et quand on rentrait "Paris 7" j'y demandais de faire str.lower() ducoup le P>p je suis bête mdrr et ça semble trop compliqué honnêtement Maintenant on peut écrire : 
- Paris2
- Paris 2
- Paris_2
Avec la capitalisation qu'on veut ça marche donc c'est good
