### ISSUE TITLE
Dans /data/ il y a des csv qui contient pas des donnes csv.

### ISSUE THREAD

**Issue by sanzelda** [The-Weather-TEAM/Life-SCORE#56]
Fichiers avec du HTML au lieux de du csv dedans:  `polluants.csv`  `type_loyers.csv`  `observ_stat_meteo.csv`
Fichiers avec du markdown (je crois) au lieux de du csv dedans:  `eco_quartiers_2016.csv` (`info_touristiques.csv`  ?)

`loi_montagne.exe` et `ZUS.csv` est meme pas lisible (en langage machine/binaire)

Je sais pas si c'est normal ou si vous avais just pas encore traité ça. Mis je le dit quand meme.

**Comment by bosy0** [comment]
Mince cest étrange, je vais voir ça ça vient sûrement des màj qui doivent récupérer un fichier non csv 😕

**Comment by bosy0** [comment]
Ok je viens de vérifier, c'est enfait pas directement des csv qu'on télécharge mais genre des pages internet qui redirige vers un csv, à corriger je m'en occupe peut être avec @fredericmarquet

**Comment by bosy0** [comment]
Pour loi montagne, c'est top chiant parce qu'enfait c'est un fichier excel, je pense qu'on va revoir toute notre base de données de csv de toute façon maintenant c'est facile à modifier
