### ISSUE TITLE
Fichier csv/txt pour mémoire du dico 

### ISSUE THREAD

**Issue by Spaghet34** [The-Weather-TEAM/Life-SCORE#58]
On crée un fichier au lancement du programme et si il existe déjà on récupère les données (on ne fait le QCM qu'une fois du coup ) 
A voir si on propose de le refaire ou pas mais c'est faisable je pense

**Comment by bosy0** [comment]
ultra chaud, si t'as besoin d'un coup de main go

**Comment by Spaghet34** [comment]
Vas-y top jpensais créer un csv du style
0, clé,val
1,...,...
2,...,...
....
Et du coup vérification de l'existante et de savoir si le fichier est vide genre si ya que la première ligne le QCM est pas fait et pour le rajouter on peut faire
`With open('blabla.csv", 'w') as fichier :
       For tuples in dico_reponses.getitems():
              Ajouter tuples[0] dans csv[cle] 
              Ajouter tuples[1] dans CSV[val]`

**Comment by Spaghet34** [comment]
C'est fait mouahahah
