### ISSUE TITLE
Animation note

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#61]
![image](https://user-images.githubusercontent.com/104134380/212503086-00baa629-df85-4cdd-9d85-2687a8285ae4.png)
regardez moi ce schéma de ouf

en gros l'idée c'est de faire une animation de la note avec une fonction sympa comme ça au début ça va lentement, puis après vite et toute à la fin ça ralenti pour donner un effet glissant quoi mdrr 
Je m'en occupe j'ai déjà une idée en tête

![image](https://media.tenor.com/AkaJe_vlXkQAAAAC/thousand-and-growing.gif)
Genre un truc comme ça mais en plus classe encore

**Comment by bosy0** [comment]
couleur= couleur_score(score)
        score_total_animation = score
        score = str(score)
        
        
      

        
        # ANIMATION DU SCORE 
        # problème lol : c'est sympa mon idée mais enfait ça fait juste freeze le temps que l'animation marche ducoup c'est nul mdrr, si vous 
        # avez une solution c'est avec grand plaisir ptdrr - Nathan
        
        if score != 'N/A':
            
            for i in range(score_total_animation+1) :
            
                #Textes :
                msg_note = customtk.CTkLabel(windowScore, text=f'Note : \n' + str(i) +'  ' ,text_color =couleur, font =('Franklin gothic medium',40), justify=CENTER)
                msg_note.place(relx=0.9,rely=0.1, anchor=CENTER)#Nord Est
                
                
                msg_bonus = customtk.CTkLabel(windowScore,text=plus, width = 1000, font =('Bold',30), justify=LEFT)
                msg_malus = customtk.CTkLabel(windowScore,text=moins, width = 1000, font =('Bold',30), justify=LEFT)
                msg_bonus.place(relx = 0.15, rely = 0.7,anchor = CENTER)
                msg_malus.place(relx=0.8,rely=0.7,anchor = CENTER)

                sleep(0.001)
        
        
        else:
            
            #Textes :
            msg_note = customtk.CTkLabel(windowScore, text=f'Note : \n' +score +'  ' ,text_color =couleur, font =('Franklin gothic medium',40), justify=CENTER)
            msg_note.place(relx=0.9,rely=0.1, anchor=CENTER)#Nord Est
            msg_NonAttribue = customtk.CTkLabel(windowScore,text="Nous n'avons pas pu récuperer les informations de cette ville", width = 1000, font =('Bold',30), justify=LEFT)
            msg_NonAttribue.place(relx = 0.5, rely = 0.5,anchor = CENTER)




J'ai voulu faire ça mais ça déconne mdr

**Comment by Spaghet34** [comment]
Ah ouais genre comme dans Mario galaxy 2 quand tu donnes des cristaux aux lumas mdrr
Tu peux ptêtre diviser la note en 6 par exemple (75/6 ≈ 12)
Et tous les 12 points t'accelere

**Comment by Spaghet34** [comment]
T'as l'option msg.configure pour modifier le texte mais le problème principal viensd e sleep qui bloque tout le programme pendant X secondes

**Comment by bosy0** [comment]
ah oui c'est lui qui casse les couilles mdrrr, je vais voir si y'a pas une autre fonction qui peut ne pas bloquer tt le programme

**Comment by Spaghet34** [comment]
Une autre solution serait de créer les 100 messages différents et de les placer un par un mais c'est un peu long mdrr

**Comment by bosy0** [comment]
oof ouais

**Comment by bosy0** [comment]
après si ça pourrait marcher de mettre la note à la fin du code dans LifeSCORE go si c'est pas trop pénible

**Comment by bosy0** [comment]
Tout beau tout propre
