### ISSUE TITLE
Bug (pas grave) sur les animations et tkinter

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#62]
invalid command name "2026196110976update"
    while executing
"2026196110976update"
    ("after" script)
invalid command name "2026211505088check_dpi_scaling"
    while executing
"2026211505088check_dpi_scaling"
    ("after" script)
invalid command name "2026211594496_click_animation"
    while executing
"2026211594496_click_animation"
    ("after" script)
invalid command name "2026211604352_click_animation"
    while executing
"2026211604352_click_animation"
    ("after" script)

**Comment by Spaghet34** [comment]
Je l'ai référencé dans #52 il me semble

**Comment by bosy0** [comment]
ah yes pardon
