### ISSUE TITLE
Ajout conditions si le csv ne prend pas le code INSEE

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#63]
pour l'instant le programme de récup de données automatique fonctionne au top, mais seulement si le fichier csv en question prend en compte le code INSEE. Il faut rajouter une condition qui fait que si le code INSEE n'est pas compatible, on prend le nom de la ville (et à ce moment là on le transforme en MAJ/MIN en fonction du csv)

**Comment by Spaghet34** [comment]
Sinon on télécharge des données qui prennent uniquement les codes insee et pour la conversion on se fait pas chier on prend les deux en .lower()

**Comment by bosy0** [comment]
grave c'est bcp plus simple mdrr, bien vu bg

**Comment by Farenc21** [comment]
ducoup ? tu comptes faire les csv sans code Insee ou pas ? On a quand même une base de données sympa et c'est vrai que ça rajouterai pas mal de code, à voir

**Comment by bosy0** [comment]
Franchement je pense que même si ça prend la tête c'est pas mal de le faire, au moins ça rajoute au facteur de la compatibilité des csv

**Comment by Farenc21** [comment]
Super ! concentre toi sur ça et je m'occupe de l'issue #101 si tu veux

**Comment by bosy0** [comment]
vsy go

**Comment by bosy0** [comment]
ça marche, c'est parfait, j'adore l'informatique, j'adore lifescore
