### ISSUE TITLE
Image pas affichée partout ?

### ISSUE THREAD

**Issue by Spaghet34** [The-Weather-TEAM/Life-SCORE#64]
![image](https://user-images.githubusercontent.com/101197359/212564295-858c9cb1-e5a6-46a1-81af-65dbd912577b.png)
En haut a gauche elle est affichée mais elle ne l'est pas dans la barre des tâches c'est dommage

**Comment by bosy0** [comment]
C'est super étrange parce que même sans mettre de logo j'ai pas le même truc, tu le lances sur vscode direct on est d'accord ? mdrr

**Comment by Spaghet34** [comment]
ouais direct c'est bizarre

**Comment by sanzelda** [comment]
Je crois qu'on peut que faire ça une fois qu'on le transforme en .exe

**Comment by bosy0** [comment]
ah parfait

**Comment by bosy0** [comment]
https://github.com/TomSchimansky/CustomTkinter/issues/879
https://github.com/TomSchimansky/CustomTkinter/wiki/CTkImage

**Comment by bosy0** [comment]
Corrigé sur le dernier commit, pour moi ça marche parfaitement avant ça bugais quelques fois. Je sais pas si c'est corrigé pour raph (j'espère mdr)
