### ISSUE TITLE
Créer styles.CSV sur update.py

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#65]

**Comment by bosy0** [comment]
@Spaghet34 j'ai créer un fichier csv options.csv comme ça au lieu de stocker juste le style on peut stocker la fréquence de maj, et des autres paramètres si on veut en rajouter

**Comment by Spaghet34** [comment]
Parfait ce soir je le raccorde à Life score pour le lire et c'est bon

**Comment by bosy0** [comment]
ça marche si jamais tu peux piquer dans update.py vas-y y'a pas mal de commentaires
et s

**Comment by bosy0** [comment]
Enfait raph laisse tomber y'a juste à direct le faire quand on modifie la valeur

**Comment by bosy0** [comment]
mettre les  données de base :
- style : system
- maj : tous les mois
