### ISSUE TITLE
Ajouts CSV dans la base de données

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#67]
Ajouter au moins une dizaine de csv pour pouvoir les intégrer à la notation et plus mettre une note qui prend seulement en compte les établissements sportifs.

Il faut pas regarder sur data.gouv.fr, il faut voir quelles sont les données les plus importantes pour noter une ville puis seulement près regarder le csv qui nous intéresse sur data.gouv.fr

**Comment by Farenc21** [comment]
On a assez de CSV mdrr
