### ISSUE TITLE
Faire màj des bibliothèques en fonction de la fréquence de MAJ (options.csv)

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#68]
Tu en penses quoi @sanzelda ? Comme ça on ne fait pas la vérification de mise à jour à chaque lancement..
Si t'es ok je m'en occupe

**Comment by sanzelda** [comment]
ouai ça l'aire un bonne idee. Mais il faut que ça tourne au moins 1 fois pour le premier fois qu'ils lancent le programme.

**Comment by bosy0** [comment]
yes ! de toute façon on le fait aussi avec les csv : si la première installation on a pas les fichiers requis, on lance pas le programme

**Comment by sanzelda** [comment]
ok parfait alors
