### ISSUE TITLE
Doublon dans LifeSCORE entre customtkinter et customtk

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#70]
@Spaghet34 en fait on a des lignes où c'est customtkinter et d'autres où c'est customtk :/

**Comment by Spaghet34** [comment]
Si t'as 30 secondes fais ctrl F et fais rechercher et remplacer customtkinter par customtk (sauf le premier où on import customrk

**Comment by bosy0** [comment]
je fais ça
