### ISSUE TITLE
Réduire la taille du texte (de la ville) 

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#71]
La réduire en fonction de sa longueur et en prenant en compte la taille de la fenêtre

**Comment by Farenc21** [comment]
![image](https://user-images.githubusercontent.com/101197359/213908209-9e629f3b-87c9-4667-af2c-256fd7f4f8f8.png)
![image](https://user-images.githubusercontent.com/101197359/213908210-84ae56ed-5326-471d-b244-8b5b66bf74bc.png)
c'est plpus ou moins bon j'ai pris une très grande et une très petite ville en nom et ça a l'air de marcher
j'ai fait len(ville)*-1.5 + 70 pour la taille de police (a modifier si necessaire)
