### ISSUE TITLE
Versions.csv mal écrit (lecture -> buggée)

### ISSUE THREAD

**Issue by Farenc21** [The-Weather-TEAM/Life-SCORE#73]
![image](https://user-images.githubusercontent.com/101197359/213863665-4d7fe73c-5b94-461a-a9c9-431c861d87e5.png)
Le fichier écrit deux lignes sur la même au lieu d'aller plus loin

**Comment by bosy0** [comment]
rajout_donnee = csv.writer(open(repertoire+'/'+'versions.csv', "a")) # le "a" c'est l'équivalent de .append() pour les tableaux

SANS LE newline=""

**Comment by Farenc21** [comment]
facile a faire alors parfait

**Comment by bosy0** [comment]
yes easy
