### ISSUE TITLE
Bug changement de style

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#75]
quand on va dans les paramètres pour changer le style, c'est toujours 'système' qui apparait même si on l'a définit sur autre chose

**Comment by Farenc21** [comment]
ah oui c'est moi jvais le régler (en gros quand je l'ouvre je m'occupe pas de la valeur en cours

**Comment by Farenc21** [comment]
c'est fait mais par contre ça l'affiche en anglais 
Ou alors on peut juste afficher en première valeur 'Choisissez un style'

**Comment by Farenc21** [comment]
Fait j'ai remplacé par "Styles" comme ça c'est bon
