### ISSUE TITLE
Garder le texte "Note :" même si ya un score

### ISSUE THREAD

**Issue by Farenc21** [The-Weather-TEAM/Life-SCORE#76]
pour l'instant on le voit que si on a N/A ce serait ptetre bien de le voir meme avec le score pcq ca fait bizarre après quand on réduit la fenetre 
![image](https://user-images.githubusercontent.com/101197359/213908281-62bfc924-eafe-42d5-81e3-0d70de3c0d90.png)

**Comment by bosy0** [comment]
Ah ouais j'avoue par contre mdrrr c'est quoi ce bled jpp

**Comment by Farenc21** [comment]
fait
faudrait peut etre rajouter un message pour que ca reste noir pcq la ducoup j'ai "note :" de la meme couleur que le score (avec la couleur qui varie)
