### ISSUE TITLE
ajoutez cette extension elle est sympa 

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#79]
https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments

**Comment by ThorsThunder04** [comment]
Aaah oui c'est cool

**Comment by bosy0** [comment]
![image](https://user-images.githubusercontent.com/104134380/214851027-85cd0abf-8d8e-4f47-bddb-72f67c8fa647.png)
quelques exemples (c'est pas en pytho mais ça marche pareil)
