### ISSUE TITLE
Redémarrer le programme après la nouvelle installation de nouvelles bibliothèques

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#80]

**Comment by Farenc21** [comment]
C'est a dire ?
Genre si on a pas installé pyglet quand il l'installe on redémarre ?

**Comment by bosy0** [comment]
yep ou sinon ça marche pas

**Comment by Farenc21** [comment]
Faut essayer de trouver un moyen de le faire marcher pcq c'est dommage de lancer deux fois le programme

**Comment by Farenc21** [comment]
Sinon one le mentionne pas et bon 🤷

**Comment by bosy0** [comment]
mdrrr au pire si y'a des maj on termine le programme avec un message sur le terminal

**Comment by bosy0** [comment]
c'est bon corrigé
