### ISSUE TITLE
Changement d'apparence

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#82]
ça marche pas du tout mdrr, mais thor m'a donné une idée de tout sauvegarder dans un fichier json

**Comment by Farenc21** [comment]
Mais wtf c'est censé marcher moi ça marchait quand je l'ai commit

**Comment by Farenc21** [comment]
C'est pcq t'as modifié le nom des variables avant j'avais mis un truc du genre
With open style.txt as txt:

Et plus moins With open bouton_style as bouton_txt:
Et ya plus que du txt alors il doit pas comprendre quel txt est lequel

**Comment by Farenc21** [comment]
J'ai tenté une modif mais je peux pas tester mtn dis moi si le theme clair marche @bosy0

**Comment by bosy0** [comment]
ça marche parfait

**Comment by Farenc21** [comment]
Top jsp pk ya du cette erreur le clair était devenu light
