### ISSUE TITLE
Erreur sur fermeture de page d'aide

### ISSUE THREAD

**Issue by Farenc21** [The-Weather-TEAM/Life-SCORE#86]
Comme dit en #85 , le problème est complexe à expliquer mais facile à comprendre
- J'ouvre la première page d'aide
- sans fermer cette page je passe à la suite (sur la page de recherche) donc le bouton de la page d'aide a été supprimé pendant qu'il était en état bloqué
- Je décide de fermer la fenêtre d'aide car elle encombre mon écran
- La fonction lancée à la fermeture qui doit changer l'état du bouton ressors une erreur puisque ce bouton n'existe plus
Ca me laisse plusieurs choix pour résoudre dites moi lequel est le meilleur svp @bosy0 @fredericmarquet @ThorsThunder04 :
> Mettre une condition sur le fait que le bouton soit existant

> Fermer toutes les pages d'aides en changeant de page (ça poserait un problème pour la page d'aide qu'on veut garder tout le temps

> enlever le changement d'état ( mais l'utilisateur peut ouvrir autant de pages d'aide qu'il lui plaira )

je pense partir sur la première et rajouter une suppression du bouton paramètres pour la dernière page vu qu'il nous encombre

**Comment by bosy0** [comment]
La première me semble pratique aussi
T'as besoin d'aide pour coder ou pas ça ??

**Comment by ThorsThunder04** [comment]
Je crois le premier a l'aire d'etre bien.

**Comment by Farenc21** [comment]
ok je fais ça maintenant non merci pas besoin d'aide faut juste pleins de conditions mdrr

**Comment by Farenc21** [comment]
conclu dans le commit 7db6269
