### ISSUE TITLE
Remplacer la plupart des .place par .pack

### ISSUE THREAD

**Issue by Farenc21** [The-Weather-TEAM/Life-SCORE#87]
.place pose le widget sur l'écran sans ce soucier des autres ce qui peut causer cela (cf image) 
![image](https://user-images.githubusercontent.com/101197359/220181899-71b26227-0d07-4386-a6b8-b06794d46086.png)
Tandis que .pack() se soucie des autres : Il décalera le widget si un est déjà présent là où il doit aller mais on perd en liberté de placement, voilà les seules options possibles 
![image](https://user-images.githubusercontent.com/101197359/220182327-b6b0f9aa-1914-42c9-b795-f737235079af.png)
(on a aussi un placement précis en pixel je vais me renseigner si on peut le faire avec un pourcentage)
alors dites moi ce que vous en pensez

**Comment by bosy0** [comment]
en vrai comme vous voulez, si c'est pas bcp de boulot chaud, je peux vous aider aussi

**Comment by Farenc21** [comment]
Non c'est bon on garde nos .place et peut être sur certains cas précis (avantages et inconvénients) je mettrais des .pack()
