### ISSUE TITLE
Nettoyer le code

### ISSUE THREAD

**Issue by Farenc21** [The-Weather-TEAM/Life-SCORE#90]
- Partir sur l'exemple que j'ai fait avec la fonction parametres me semble pas mal (d'abord on crée les widgets, ensuite on les places dans l'ordre
 - Respecter la syntaxe définie au début de LifeScore.py 
 - Netoyer les commentaires : Garder ceux vraiment utiles et en rajoutant d'autres

**Comment by Farenc21** [comment]
C'est terminé pour lifescore.py

**Comment by bosy0** [comment]
terminé pour update
