### ISSUE TITLE
La page de téléchargement est dernière la page principale

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#92]
js ppourquoi peut être le mainloop mais la page de téléchargement elle va toujours derrière et dcp on peut pas la voir on perd le focus

**Comment by Farenc21** [comment]
https://user-images.githubusercontent.com/101197359/222898412-83a8032f-776d-4822-a5a5-67e3aca6b581.mp4

Moi ça marche bien

**Comment by Farenc21** [comment]
` windowDownload.focus() # Ajout de cette ligne pour éviter qur ça passe derrière la page principale`
j'ai rajouté cette ligne de code

**Comment by bosy0** [comment]
trop fort le gars
