### ISSUE TITLE
Notes fausses

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#93]
![image](https://user-images.githubusercontent.com/104134380/222981602-f0382716-e538-4a76-a76a-9c2369bfbb84.png)

Il y a des moyennes supérieures au max dans la base de données et ça nous donne des résultats de fou mdrr

**Comment by fredericmarquet** [comment]
Normalement c'est bon pour les premiers CSV, je tente de modifier le reste pour ce soir

**Comment by Farenc21** [comment]
![image](https://user-images.githubusercontent.com/101197359/223132499-437ee9f8-485d-4f70-b25a-4b3caf580ee7.png)
Il me ressors n=None pour tout alors qu'on a des données sur : les écoles, les monuments, le m2 par maison, m2 par appartement et puis pour certaines données il ressors une liste avec un str au lieu d'un INT alors bon faudrait que ce soit fonctionnel après cette longue pause quoi

**Comment by Farenc21** [comment]
Prend l'exemple de Puissalicon et fais en sorte que ce que j'ai cité au dessus compte stp pcq là on dirait que rien n'a changé

**Comment by bosy0** [comment]
```
Le csv sport (test)
 - Par habitant : 0.003054849573698246
 - Note /100 : 45

Le csv population
 - Note /100 : ['79873']

Le csv communes
Fonction pas encore implémentée

Le csv ecoles
 - Total dans la ville : 162
 - Par habitant : 0.0020282197989308025
 - Note /100 : 600.9926865458082

Le csv colleges
 - Total dans la ville : 9
 - Par habitant : 0.00011267887771837793
 - Note /100 : 59.116986218912565

Le csv lycees
 - Total dans la ville : 5
 - Par habitant : 6.259937651020996e-05
 - Note /100 : 57.52524954272401

Le csv police_gendarmerie
 - Note /100 : None

Le csv festivals
 - Note /100 : None

Le csv musees
Fonction pas encore implémentée

Le csv hopitaux
Fonction pas encore implémentée

Le csv monuments_historiques
 - Total dans la ville : 0
 - Par habitant : 0.0
 - Note /100 : 43.103448354340074

Le csv m2_maison
 - Donnée : ['9,55060514279194']
 - Note /100 : 39.849624060150376

Le csv m2_appartement
 - Donnée : ['9,93716325468111']
 - Note /100 : 38.49206349206349

Le csv jardins
Fonction pas encore implémentée

Le csv radon_nucleaire
 - Donnée : [1]
 - Note /100 : 70.0

Le csv juridictions_competentes
 - Note /100 : None

Le csv action_coeur_de_ville
 - Note /100 : None

Le csv production_electricite_gaz
 - Note /100 : None

Le csv dose_rayonnements_telluriques
 - Note /100 : None

LES NOTES : [45, 100, 59.116986218912565, 57.52524954272401, 43.103448354340074, 39.849624060150376, 38.49206349206349, 70.0]
```


On commence à avoir un truc pas mal, ce qui est bien c'est plus je fais de fonctions plus on augmente la compatibilité avec d'autres csv
