### ISSUE TITLE
Zoom de la carte qui bug

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#97]
Si on zoom 6 fois plus rien n'est affiché, jsp si y'a un moyen de le corriger

**Comment by Farenc21** [comment]
Jsp je crois que c'est bon mdrr je peux zoomer et dézoomer comme je veux

**Comment by Farenc21** [comment]
On pourra éventuellement évoquer ce problème (il ne faut pas zoomer plus de 6 fois sinon on ne voit plus rien) même si en zoomant autant, faut pas s'attendre à voir grand chose
