### ISSUE TITLE
Pas de logo dans la page paramètres

### ISSUE THREAD

**Issue by bosy0** [The-Weather-TEAM/Life-SCORE#99]
Je vais centraliser le logo de l'application avec une variable globale
![image](https://user-images.githubusercontent.com/104134380/223863444-b296bbe2-0261-491e-8264-6f0ea94edb77.png)

**Comment by Farenc21** [comment]
Je suis pas sur de comprendre ni de voir l'utilité de la variable globale :
1) Quand on crée une page on a juste a mettre une ligne genre page.icon(lien de l'image)
2) Le transformer en variable globale ne le mettra pas automatiquement

**Comment by bosy0** [comment]
non parce que on def à chaque fois une variable avec le chemin vers l'image

**Comment by Farenc21** [comment]
ah oui oui pour la redondance c'est bien
si tu peux le faire vasy sinon je le fais dans 30 min

**Comment by Farenc21** [comment]
Allez on va faire comme si rien ne s'était passé (j'ai l'impression que c'est aléatoire des fois c'est là des fois c'est c'est pas là)
